services:
  app.home_page_controller:
    class:     AppBundle\Controller\HomePageController
    arguments: ['@templating', '@router', '@session']
  app.search_controller:
    class:     AppBundle\Controller\SearchController
    arguments: ['@templating', '@router']
