sudo: false
services:
  - docker

before_script:
  - phpenv config-rm xdebug.ini

script:
  - docker-compose up -d db
  - docker-compose up -d
  - cd symfony && composer install --no-dev
  - docker exec -it finalyearproject_frontend_1 bash -lc "cd /var/www/symfony && php vendor/phpunit/phpunit/phpunit"
  - docker exec -it finalyearproject_api_1 bash -lc "cd /twitteranalyser && python -m pytest tests"
