version: '2'

volumes:
    symfony_logs:
        driver: local
    symfony_cache:
        driver: local
    nginx_logs:
        driver: local
    db_data:

services:
    db:
        image: mysql
        ports:
            - 3305:3306
        expose:
            - "3306"
        volumes:
            - ./db_data:/var/lib/mysql
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: twitter_analyser
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
            
    frontend:
        build: ./frontend
        volumes:
            - ./symfony:/var/www/symfony
            - ./symfony_logs:/var/www/symfony/app/logs
            - ./symfony_cache:/var/www/symfony/app/cache
        depends_on:
            - db

    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes_from:
            - frontend:ro
        volumes:
            - nginx_logs:/var/log/nginx

    api:
      environment:
          - PYTHONUNBUFFERED=0
      build: ./api
      restart: always
      expose:
        - "80"
      depends_on:
        - db
