version: '2'

volumes:
    symfony_logs:
        driver: local
    symfony_cache:
        driver: local
    nginx_logs:
        driver: local


services:
    rabbit:
      container_name: rabbitMQ
      image: rabbitmq:latest
      ports:
        - 5672
    db:
        container_name: database
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: twitter_analyser
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
    php:
        container_name: php_fpm
        build: ./php-fpm
        environment:
          - AMPQ_ADDRESS=amqp://rabbit:5672
        volumes:
            - ./symfony:/var/www/symfony
            - ./symfony_logs:/var/www/symfony/app/logs
            - ./symfony_cache:/var/www/symfony/app/cache
        links:
          - db:database
          - python:python
          - rabbit

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 80:80
        volumes_from:
            - php:ro
        volumes:
            - nginx_logs:/var/log/nginx

    python:
      container_name: python
      build: ./python
      environment:
        - AMPQ_ADDRESS=amqp://rabbit:5672
      expose:
        - "80"
      depends_on:
        - db
      links:
        - db:database
        - rabbit
