version: '2.1'

volumes:
    frontend_logs:
    nginx_logs:
    db_data:

services:
    db:
        build: ./mysql
        ports:
            - 3305:3306
        volumes:
            - ./mysql/db_data:/var/lib/mysql
            - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: twitter_analyser
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password

    frontend:
        build: ./frontend
        volumes:
            - ./frontend/twitteranalyser:/var/www/twitteranalyser
            - ./frontend/frontend_logs:/var/www/twitteranalyser/app/logs
        depends_on:
            db:
              condition: service_healthy

    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes_from:
            - frontend:ro
        volumes:
            - ./nginx/nginx_logs:/var/log/nginx

    api:
      environment:
          - PYTHONUNBUFFERED=0
      build: ./api
      volumes:
          - ./api/twitteranalyser:/twitteranalyser
      depends_on:
        db:
          condition: service_healthy
